{{- $config := fromYaml (include "inventory.updater.config" .) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "agent.resource.name" $config }}
  namespace: {{ $.Release.Namespace }}
  labels:
{{ include "common.labels.with.chart" $config | indent 4 }}
rules:
- apiGroups: [ "apiextensions.k8s.io" ]
  resources: [ "customresourcedefinitions" ]
  verbs: [ "*" ]

- apiGroups: [ "rbac.authorization.k8s.io" ]
  resources: [ "clusterroles", "clusterrolebindings" ]
#  resourceNames: [ "asset-mgmt-admission-enforcer", "asset-mgmt-admission-policy", "asset-mgmt-inventory-agent", "asset-mgmt-runtime-daemon" ]
  verbs: [ "get" ]

- apiGroups: [ "admissionregistration.k8s.io" ]
  resources: [ "validatingwebhookconfigurations" ]
  resourceNames: [ "cloudguard-enforcer-webhook" ]
  verbs: [ "patch", "get" ]
